### ISSUE TITLE
Criar o arquivo changelog.md

### ISSUE THREAD

**Issue by lukBarros** [afonsopacifer/open-source-boilerplate#2]
Criar o arquivo changelog.md destinado a manter o changelog textual oficial do timeline de versões (tags) distribuídas.

**Comment by lukBarros** [comment]
Sem respostas,fechei!

**Comment by afonsopacifer** [comment]
@lukBarros,
Opa, foi mau, só vi a issue hoje, não vi quando vc abriu :(
Vou criar o arquivo, se vc quiser mandar um PR adicionando o arquivo fique a vontade tbm :)
